# Generated by Django 3.0.5 on 2021-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
